version: "3.8" # Версия формата docker-compose файла

services:
  client:
    build:
      context: ./ad-client
    ports:
      - "8080:8080"
  server:
    build:
      context: ./ad-server
    ports:
      - "3000:3000"